export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCESS'

export const SIGN_OUT = 'SIGN_OUT'

export const USER_REQUEST = 'USER_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'

export const CONTACT_REQUEST = 'CONTACT_REQUEST'
export const CONTACT_SUCCESS = 'CONTACT_SUCCESS'

export const SET_ME = 'SET_ME'

export const CONTACTS_REQUEST = 'CONTACTS_REQUEST'
export const CONTACTS_SUCCESS = 'CONTACTS_SUCCESS'

export const ITEMS_REQUEST = 'ITEMS_REQUEST'
export const ITEMS_SUCCESS = 'ITEMS_SUCCESS'

export const LOCATIONS_REQUEST = 'LOCATIONS_REQUEST'
export const LOCATIONS_SUCCESS = 'LOCATIONS_SUCCESS'

export const SELECT_ITEM = 'SELECT_ITEM'
export const SELECT_CONTACT = 'SELECT_CONTACT'

export const ADD_CONTACT_REQUEST = 'ADD_CONTACT_REQUEST'
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS'

export const UPDATE_CONTACT_REQUEST = 'UPDATE_CONTACT_REQUEST'
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED'

export const APP_DATA_REQUEST = 'APP_DATA_REQUEST'
export const APP_DATA_SUCCESS = 'APP_DATA_SUCCESS'

export const EDIT_CONTACT_REQUEST = 'EDIT_CONTACT_REQUEST'
export const EDIT_CONTACT_COMPLETE = 'EDIT_CONTACT_COMPLETE'
