export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCESS'

export const USER_REQUEST = 'USER_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'

export const CONTACT_REQUEST = 'CONTACT_REQUEST'
export const CONTACT_SUCCESS = 'CONTACT_SUCCESS'

export const SET_ME = 'SET_ME'

export const CONTACTS_REQUEST = 'CONTACTS_REQUEST'
export const CONTACTS_SUCCESS = 'CONTACTS_SUCCESS'

export const SELECT_ITEM = 'SELECT_ITEM'
export const SELECT_CONTACT = 'SELECT_CONTACT'

export const ADD_CONTACT_REQUEST = 'ADD_CONTACT_REQUEST'
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS'

export const UPDATE_CONTACT_REQUEST = 'UPDATE_CONTACT_REQUEST'
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
