export const getUser = jest.fn(() => Promise.resolve([]))
export const postLogin = jest.fn(() => Promise.resolve([]))
export const postSignup = jest.fn(() => Promise.resolve([]))
export const getContacts = jest.fn(() => Promise.resolve([]))
export const postContact = jest.fn(() => Promise.resolve([]))
export const putContact = jest.fn(() => Promise.resolve([]))
